# Generated by Django 4.2.15 on 2024-08-22 11:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlowerPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=8)),
                ('upload_image', models.URLField()),
                ('text', models.TextField(max_length=1000)),
            ],
        ),
    ]
