# Generated by Django 4.2.15 on 2024-08-23 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('flowerposts', '0002_remove_flowerpost_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowerpost',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='flowerposts', to='categories.category'),
            preserve_default=False,
        ),
    ]
